services:
  rent_api:
    container_name: rent_api
    build: .
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - JWT_SINGING_KEY=${JWT_SINGING_KEY}
      - DB_MIGRATION_FLAG=${DB_MIGRATION_FLAG}
      - API_PORT=${API_PORT}
    ports:
      - ${API_PORT}:9090
    depends_on:
      - rent_db
    volumes:
      - .:/app
    command: air

  rent_db:
    container_name: rent_db
    image: postgres:16.2
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes: 
      - ./db-data:/var/lib/postgresql/data